name: orientdb_dart
version: 0.1.0
author: SoftHai <softhai@gmx.de>
description: A dart client to get access to an OrientDB instance
homepage: https://github.com/SoftHai/OrientDB.dart
documentation: http://www.dartdocs.org/documentation/orientdb_dart/latest/index.html
dependencies:
  http: '>=0.11.1+1 <0.12.0'
